{
  "hash": "9215229a9f5a01e129fbc93ca9b769ad",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Rasters on S3\"\nbread-crumbs: false\n---\n\n\n\nSatellite archives live in object storage, and the pipelines that consume them increasingly\nwrite their outputs back there too. `freezecore.raster` exists so that reading and writing\nthose rasters looks the same whether the file is on local disk or in a bucket.\n\n## The problem it solves\n\n`rasterio` can already open an `s3://` URI — GDAL's `/vsis3/` driver handles it. What it\ncannot do is work out *which* credentials to use. That is configured through GDAL\nenvironment variables (`AWS_ACCESS_KEY_ID`, `AWS_S3_ENDPOINT`, `AWS_NO_SIGN_REQUEST`, and\na dozen more), set globally, at a different layer from the path you are opening.\n\nThe result is code that carries credentials in one place and paths in another, and breaks\nin confusing ways when a pipeline touches two different object stores in one process.\n\n`freezecore` attaches the credentials to the path itself. `make_s3_upath()` builds a\n`UPath` that carries its storage options, and `rasterio_open()` reads those options back\nout and installs them into a GDAL environment for exactly the duration of the `with`\nblock:\n\n```python\nfrom freezecore.raster import rasterio_open\nfrom freezecore.s3 import make_s3_upath\n\npath = make_s3_upath(\"s3://my-bucket/scene.tif\", key=..., secret=...)\nwith rasterio_open(path) as src:\n    data = src.read(1)\n```\n\nBecause the configuration travels with the path, two stores in the same process do not\ninterfere, and `rasterio_open()` is otherwise a drop-in replacement for `rasterio.open()`\n— a plain `Path` or `str` opens a local file with no S3 machinery involved.\n\n::: {.callout-note}\n## Requires the `s3` extra\n\n`freezecore.s3` needs `s3fs`, `fsspec`, and `boto3`. Install with\n`pip install \"freezecore[s3] @ git+https://github.com/lqgentner/freezecore.git\"`. The\nimport is lazy, so `freezecore.raster` works for local files without the extra.\n:::\n\n## A real, public example\n\nThe [Copernicus DEM GLO-30](https://registry.opendata.aws/copernicus-dem/) is a global\n30 m elevation model published on the AWS Open Data registry. The bucket is public, so\nomitting `key` and `secret` sends unsigned requests and no account is needed:\n\n::: {#95083ec1 .cell execution_count=2}\n``` {.python .cell-code}\nfrom freezecore.raster import rasterio_open\nfrom freezecore.s3 import make_s3_upath\n\n# GLO-30 is tiled into 1° x 1° COGs named by their south-west corner.\ntile = \"Copernicus_DSM_COG_10_N46_00_E008_00_DEM\"\ndem_path = make_s3_upath(\n    f\"s3://copernicus-dem-30m/{tile}/{tile}.tif\",\n    region=\"eu-central-1\",\n)\n\nwith rasterio_open(dem_path) as src:\n    print(f\"driver:     {src.driver}\")\n    print(f\"crs:        {src.crs}\")\n    print(f\"shape:      {src.shape}\")\n    print(f\"dtype:      {src.dtypes[0]}\")\n    print(f\"bounds:     {tuple(round(v) for v in src.bounds)}\")\n    print(f\"overviews:  {src.overviews(1)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndriver:     GTiff\ncrs:        EPSG:4326\nshape:      (3600, 3600)\ndtype:      float32\nbounds:     (8, 46, 9, 47)\noverviews:  [2, 4, 8]\n```\n:::\n:::\n\n\nNote what the source looks like: geographic coordinates (EPSG:4326), 3600 × 3600 pixels\nspanning a whole degree, with a pixel size in fractions of a degree rather than metres.\nIt is a perfectly good DEM and completely unusable as a stacking target.\n\n## Resampling onto a grid square\n\nThis is where the [MGRS grid](mgrs-grid.qmd) pays off. An `MGRSGeoBox` carries the\nthree things `rasterio.warp.reproject` needs for its destination — `crs`, `transform`,\nand `shape` — so the resampling call needs no other geospatial arguments:\n\n::: {#bf3e0975 .cell execution_count=3}\n``` {.python .cell-code}\nimport numpy as np\nfrom rasterio.warp import Resampling, reproject\n\nfrom freezecore.mgrs import MGRSGeoBox\n\nsquare = MGRSGeoBox.from_mgrs(\"32TMS35\", resolution=10.0)\n\ndem = np.full(square.shape.yx, np.nan, dtype=\"float32\")\nwith rasterio_open(dem_path) as src:\n    reproject(\n        source=src.read(1),\n        destination=dem,\n        src_transform=src.transform,\n        src_crs=src.crs,\n        dst_transform=square.transform,\n        dst_crs=square.crs,\n        dst_nodata=np.nan,\n        resampling=Resampling.bilinear,\n    )\n\nprint(f\"{square.mgrs_code}: {dem.shape} px @ {square.resolution.x} m in {square.crs}\")\nprint(f\"elevation: {np.nanmin(dem):.0f} m - {np.nanmax(dem):.0f} m\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n32TMS35: (1000, 1000) px @ 10.0 m in EPSG:32632\nelevation: 1931 m - 4085 m\n```\n:::\n:::\n\n\nThe DEM is now a 1000 × 1000 array in EPSG:32632 at exactly 10 m — the same array shape,\nCRS, and transform that every other source resampled onto `32TMS35` will have. That is the\nentire point of fixing the grid first.\n\n::: {#3e6ac171 .cell execution_count=4}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nleft, bottom, right, top = square.boundingbox\nfig, ax = plt.subplots(figsize=(6.5, 5.5))\nim = ax.imshow(dem, cmap=\"terrain\", extent=(left, right, bottom, top))\nfig.colorbar(im, ax=ax, label=\"elevation (m)\", shrink=0.85)\nax.set_title(f\"MGRS {square.mgrs_code}\")\nax.set_xlabel(\"easting (m)\")\nax.set_ylabel(\"northing (m)\")\nax.ticklabel_format(style=\"plain\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Copernicus DEM GLO-30 resampled onto MGRS grid square 32TMS35 (Fiescher/Aletsch area, Bernese Alps) at 10 m.](rasters-on-s3_files/figure-html/cell-5-output-1.png){width=598 height=468}\n:::\n:::\n\n\n::: {.callout-tip}\n## Pick squares that fit their source tile\n\nGLO-30 tiles are 1° × 1°, and MGRS squares do not respect degree boundaries. `32TMS35`\nhappens to sit entirely inside the `N46/E008` tile; a square straddling 8° E would need\nboth neighbouring tiles, leaving a nodata stripe if only one is read. `merge_tiffs()`\nhandles that case, or read the sources through a `rasterio.vrt.WarpedVRT` mosaic.\n:::\n\n## Writing the result back\n\n`write_cog()` takes the array straight to a Cloud-Optimized GeoTIFF, staging through an\nin-memory file and applying `COG_PROFILE`'s compression and overview settings. Again the\n`GeoBox` supplies the georeferencing:\n\n::: {#e7bb68c2 .cell execution_count=5}\n``` {.python .cell-code}\nfrom freezecore.raster import write_cog\n\nprofile = {\n    \"dtype\": \"float32\",\n    \"count\": 1,\n    \"width\": square.shape.x,\n    \"height\": square.shape.y,\n    \"crs\": square.crs,\n    \"transform\": square.transform,\n    \"nodata\": np.nan,\n}\n\nwrite_cog(dem, f\"dem_{square.mgrs_code}.tif\", profile, band_names=[\"elevation\"])\n```\n:::\n\n\nThe destination may equally be an S3 `UPath`, in which case the object is written with a\nsingle atomic `PutObject`:\n\n```python\ndst = make_s3_upath(f\"s3://my-bucket/dem/{square.mgrs_code}.tif\", key=..., secret=...)\nwrite_cog(dem, dst, profile, band_names=[\"elevation\"])\n```\n\nFor files that already exist, `rewrite_tiff()` does the same job without loading the array\nyourself — recompressing, retiling, renaming bands, or moving between backends. Source and\ndestination credentials are resolved independently, so S3-to-S3 copies across two\ndifferent stores work:\n\n```python\nfrom freezecore.raster import COG_PROFILE, rewrite_tiff\n\nrewrite_tiff(\"scene.tif\", dst, profile=COG_PROFILE)             # local -> S3, as COG\nrewrite_tiff(src_on_store_a, dst_on_store_b, move=True)         # S3 -> S3, then delete\n```\n\n## Listing objects\n\nOne gap worth knowing about. `make_s3_upath()` configures anonymous access for *GDAL*, via\n`rasterio_open()`, but it has no `anon` passthrough to `s3fs`. Filesystem-level operations\non the returned path — `.exists()`, `.iterdir()`, `.glob()` — therefore still try to sign\ntheir requests and fail on a public bucket with `NoCredentialsError`.\n\nUntil that is exposed, use a plain `UPath` with `anon=True` for listing:\n\n::: {#b83daa45 .cell execution_count=6}\n``` {.python .cell-code}\nfrom upath import UPath\n\nbucket = UPath(\"s3://copernicus-dem-30m/\", anon=True)\n[p.name for p in list(bucket.iterdir())[:3]]\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n['Copernicus_DSM_COG_10_N00_00_E006_00_DEM',\n 'Copernicus_DSM_COG_10_N00_00_E009_00_DEM',\n 'Copernicus_DSM_COG_10_N00_00_E010_00_DEM']\n```\n:::\n:::\n\n\nReading is unaffected — `rasterio_open()` on a `make_s3_upath()` path works anonymously,\nas everything above this section demonstrates.\n\n## Related helpers\n\n`freezecore.raster` carries a few more utilities that come up in the same pipelines:\n\n| Function | Use |\n|---|---|\n| `merge_tiffs()` | Mosaic several GeoTIFFs, grouping by CRS |\n| `group_tiffs_by_crs()` | Partition a file list by CRS before merging |\n| `build_rasterio_profile()` | Merge profile dicts onto sensible defaults |\n| `get_utm_zone_string()` / `utm_zone_to_crs()` | Convert between UTM zone strings and CRS |\n\nSee the [API reference](../reference/index.qmd) for full signatures.\n\n",
    "supporting": [
      "rasters-on-s3_files"
    ],
    "filters": [],
    "includes": {}
  }
}